### ISSUE TITLE
Example doesn't work without importing `MobiledocButton`

### ISSUE THREAD

**Issue by mccallofthewild** [alidcastano/vue-mobiledoc-editor#6]
The basic usage example threw this error:
```
[Vue warn]: Unknown custom element: <mobiledoc-button> - did you register the component correctly? For recursive components, make sure to provide the "name" option. 
```
The fix was easy. I just imported & registered the button component too.
``` javascript
  import { MobiledocEditor, MobiledocToolbar, MobiledocButton } from "vue-mobiledoc-editor"

  export default {
    components: {
      MobiledocEditor,
      MobiledocToolbar,
      MobiledocButton
    }
  }
```
Not a major issue, but an update to the docs might be good. 👍

**Comment by alidcastano** [comment]
That's strange, I would imagine that it would be sufficient for the `MobiledocToolbar` component to register its `MobiledocButton`. Were you using the mobiledoc button separately as well? 

Either way, this plugin is going to undergo an API change soon since Vue@2.3 released provide/inject capabilities for functional components (see issue https://github.com/alidcastano/vue-mobiledoc-editor/issues/3), which will make the `MobiledocEditor`easier to use and maintain. 

I'm closing this issue since I will be working on the docs after that change. But thanks for bringing this up, it's always helpful to make sure documentation is accurate.

**Comment by alidcastano** [comment]
@mccallofthewild I ended up not changing the plugin to using provide and inject as it was not possible (https://github.com/vuejs/vue/issues/5194).

But I fixed the issue you raised and updated docs! 

Thanks again
